/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesAddRouteImport } from './routes/movies/add'
import { Route as MoviesMovieIdRouteImport } from './routes/movies/$movieId'
import { Route as MoviesMovieIdEditRouteImport } from './routes/movies/$movieId_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesAddRoute = MoviesAddRouteImport.update({
  id: '/movies/add',
  path: '/movies/add',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdEditRoute = MoviesMovieIdEditRouteImport.update({
  id: '/movies/$movieId_/edit',
  path: '/movies/$movieId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/add': typeof MoviesAddRoute
  '/movies/$movieId/edit': typeof MoviesMovieIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/add': typeof MoviesAddRoute
  '/movies/$movieId/edit': typeof MoviesMovieIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/add': typeof MoviesAddRoute
  '/movies/$movieId_/edit': typeof MoviesMovieIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/movies/$movieId'
    | '/movies/add'
    | '/movies/$movieId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/movies/$movieId'
    | '/movies/add'
    | '/movies/$movieId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/movies/$movieId'
    | '/movies/add'
    | '/movies/$movieId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  MoviesAddRoute: typeof MoviesAddRoute
  MoviesMovieIdEditRoute: typeof MoviesMovieIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/add': {
      id: '/movies/add'
      path: '/movies/add'
      fullPath: '/movies/add'
      preLoaderRoute: typeof MoviesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId_/edit': {
      id: '/movies/$movieId_/edit'
      path: '/movies/$movieId/edit'
      fullPath: '/movies/$movieId/edit'
      preLoaderRoute: typeof MoviesMovieIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  MoviesAddRoute: MoviesAddRoute,
  MoviesMovieIdEditRoute: MoviesMovieIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
